services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "1337:27017"
    volumes:
      - mongo_db_data:/data/db
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: futurama
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "1338:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql

volumes:
  mysql_db_data:
  mongo_db_data:
